# SPDX-FileCopyrightText: 2023 Davidson <twister@davidson.fr>
# SPDX-License-Identifier: CC0-1.0

version: '3.8'

services:
  backend:
    container_name: backend-php-sql-index
    build:
      context: ../
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html/test:ro
      - ../env.php:/var/www/html/env.php:ro
    network_mode: host
