version: '3.8'

services:
  backend:
    container_name: backend-php-s74
    build:
      context: ../
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html/test:ro
      - ../env.php:/var/www/html/env.php:ro
    network_mode: host
